server:
  port: 8761
  
spring:
  application:
    name: oneself-provider-user
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8760/eureka/
  instance:
    prefer-ip-address: true