server:
  port: 8043
spring:
  application:
    name: oneself-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiyajing/oneself/     #配置git仓库的地址
          search-paths: /oneself-spring-cloud/config-repo #git仓库地址下的相对地址，可以配置多个，用,分割
          username: 
          password: 
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8760/eureka/