server:
  port: 8010
  
spring:
  application:
    name: oneself-consumer-movie-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@shiyajing.xyz:8760/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka #高可用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}