server:
  port: 8010
  
spring:
  application:
    name: oneself-consumer-movie-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8760/eureka/
  instance:
    prefer-ip-address: true