server:
  port: 8020
spring:
  application:
    name: oneself-consumer-movie-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8760/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka #高可用
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定