server:
  port: 8040
spring:
  application:
    name: oneself-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiyajing/oneself/     # 配置git仓库的地址
          search-paths: oneself                          # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: shiyajing1314520@126.com             # git仓库的账号
          password: s123456                              # git仓库的密码