server:
  port: 8002
  
spring:
  application:
    name: oneself-provider-qrcode
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@shiyajing.xyz:8760/eureka/
      #这个oneself-discovery-eureka-high工程代表高可用服务注册中心
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka #高可用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}