spring:
  application:
    name: oneself-consumer-movie
server:
  port: 8002
user: 
  userServicePath: http://localhost:8001/userinfo/simple/getUser/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@discovery:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}